apiVersion: v1
kind: Service
metadata:
  name: legos-backend-svc
  labels:
    app: legos-backend-svc
  namespace: legos
spec:
  selector:
    app: legos-backend-deployment
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  type: NodePort